# dashboard.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def plot_dashboard():
    # Set up clean, academic presentation styling
    plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
    fig = plt.subplots(3, 2, figsize=(14, 18), dpi=300)
    ((ax1, ax2), (ax3, ax4), (ax5, ax6)) = fig[1]
    fig = fig[0]
    
    # Load the dual-stream data files generated by your C engine
    df_metrics = pd.read_csv('metrics.csv')
    df_heatmap = pd.read_csv('evolution_consensus.csv')
    
    # -----------------------------------------------------------------
    # PANEL 1: Fitness Curve (Standard Optimization Proof)
    # -----------------------------------------------------------------
    ax1.plot(df_metrics['Generation'], df_metrics['FitnessScore'], color='#007AFF', linewidth=2.5, label='Target Affinity Optimization')
    ax1.set_title('1. Target Fitness Convergence Trajectory', fontsize=12, fontweight='bold', pad=10)
    ax1.set_xlabel('Generations', fontsize=10)
    ax1.set_ylabel('Raw Fitness Score', fontsize=10)
    ax1.legend(loc='lower right')
    
    # -----------------------------------------------------------------
    # PANEL 2: Negative Design Decay (Proof of Safety/Cross-Reactivity Protection)
    # -----------------------------------------------------------------
    ax2.plot(df_metrics['Generation'], df_metrics['DecoyPenalty'], color='#FF3B30', linewidth=2.5, label='Off-Target Cross-Reactivity Penalty')
    ax2.set_title('2. Negative Design Decay & Safety Profiles', fontsize=12, fontweight='bold', pad=10)
    ax2.set_xlabel('Generations', fontsize=10)
    ax2.set_ylabel('Penalty Magnitude', fontsize=10)
    ax2.legend(loc='upper right')
    
    # -----------------------------------------------------------------
    # PANEL 3: Evolutionary Consensus Heatmap (The Mass-Appeal Centerpiece)
    # -----------------------------------------------------------------
    # Drop generation column to isolate just the positional integer matrix
    heatmap_data = df_heatmap.drop(columns=['Generation']).to_numpy().T
    
    # Generate the heatmap visual tracking the crystallization of amino acids
    sns.heatmap(heatmap_data, ax=ax3, cmap='turbo', cbar=False, xticklabels=10, yticklabels=2)
    ax3.set_title('3. Evolutionary Sequence Logo Consensus Heatmap', fontsize=12, fontweight='bold', pad=10)
    ax3.set_xlabel('Generations (x100 Snapshot Windows)', fontsize=10)
    ax3.set_ylabel('Sequence Position (1-21)', fontsize=10)
    
    # -----------------------------------------------------------------
    # PANEL 4: Conformational Folding Stability (Chou-Fasman Locking)
    # -----------------------------------------------------------------
    ax4.plot(df_metrics['Generation'], df_metrics['ChouFasman'], color='#34C759', linewidth=2.5, label='Chou-Fasman α-Helix Propensity')
    ax4.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7, label='Stable Helix Threshold (1.0)')
    ax4.set_title('4. Conformational Folding & Structural Stability', fontsize=12, fontweight='bold', pad=10)
    ax4.set_xlabel('Generations', fontsize=10)
    ax4.set_ylabel('Propensity Score', fontsize=10)
    ax4.legend(loc='lower right')
    
    # -----------------------------------------------------------------
    # PANEL 5: Amphipathic Vector Profile (Eisenberg Solubility Vector Magnitude)
    # -----------------------------------------------------------------
    ax5.plot(df_metrics['Generation'], df_metrics['Eisenberg'], color='#AF52DE', linewidth=2.5, label='Eisenberg Hydrophobic Moment Vector (μH)')
    ax5.set_title('5. Amphipathic Spatial Vector Profile', fontsize=12, fontweight='bold', pad=10)
    ax5.set_xlabel('Generations', fontsize=10)
    ax5.set_ylabel('Vector Magnitude (μH)', fontsize=10)
    ax5.legend(loc='lower right')
    
    # -----------------------------------------------------------------
    # PANEL 6: Thermodynamic Solvation Energy Minimization (ΔG Solvation)
    # -----------------------------------------------------------------
    ax6.plot(df_metrics['Generation'], df_metrics['SolvationEnergy'], color='#FF9500', linewidth=2.5, label='Solvation Free Energy (ΔG_solv)')
    ax6.set_title('6. Thermodynamic Solvation Free Energy Minimization', fontsize=12, fontweight='bold', pad=10)
    ax6.set_xlabel('Generations', fontsize=10)
    ax6.set_ylabel('Solvation Energy Units', fontsize=10)
    ax6.legend(loc='upper right')
    
    # Final cosmetic layout polish
    plt.suptitle('Silicon Virovore Generational Pipeline — 10,000 Generation Biophysical Suite', fontsize=16, fontweight='bold', y=0.96)
    plt.tight_layout(rect=[0, 0.03, 1, 0.93])
    
    # Save chart out directly to directory
    plt.savefig('virovore_dashboard.png', dpi=300)
    print("[PYTHON] Dashboard rendering successful! Saved as 'virovore_dashboard.png'.")

if __name__ == '__main__':
    plot_dashboard()